---
title: Sciblog
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
email: airrayagroup@gmail.com
description: ''
baseurl: "/sciblog"
url: ''
author: AIRRAYA
gems:
- jekyll-paginate
markdown: kramdown
paginate: 5
paginate_path: page:num/
comments: true
excerpt_separator: "<!-- more -->"
