---
title: LTP
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
email: prasad@letstalkpayments.com
description: 
baseurl: ''
url: 
author: LTP
gems:
- jekyll-paginate
markdown: kramdown
paginate: 5
paginate_path: page:num/
comments: true
excerpt_separator: "<!-- more -->"
